# -*- coding: utf-8 -*-
"""lec-1_fine_tuning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JILH2Ww60sMPukd-7jkJM11L5uzG0ccg
"""

import torch
from torch import nn
import numpy as np
from torch.utils.data import DataLoader
from torch.optim import AdamW

from datasets import load_dataset
from transformers import ( AutoTokenizer ,
                          AutoModelForSequenceClassification ,
                          get_linear_schedule_with_warmup)

from sklearn.metrics import accuracy_score,classification_report
from tqdm import tqdm

!pip uninstall torchvision -y

import os
os.kill(os.getpid(), 9)  # force restart runtime

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
print(torch.cuda.get_device_properties())
print(torch.cuda.get_device_name())
print(torch.cuda.get_device_properties().total_memory)

pip install torch transformers datasets scikit-learn tqdm accelerate

"""`Block 1 | Configuration`"""

CONFIG = {
    #model
    "model_name" : "bert-base-uncased",
    "num_labels" :2,


    #Tokenizer
    "max_length" :256,
    "truncation" :True,
    "padding"    :"max_length",

    # Training

    "batch_size"  :16,
    "num_epochs"  :3,
    "lr"          :2e-5,
    "weight_decay":0.01,
    "warmup_ratio":0.1,

    # Misc

    "seed"        :42,
    "save_path"   :"./bert_imdb_finetuned",
    "train_subset":None,
    "test_subset" :None,
}

"""`Block 2 | REPRODUCIBILITY & DEVICE SETUP`"""

torch.manual_seed(CONFIG["seed"])
np.random.seed(CONFIG["seed"])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

"""`BLOCK 3 │ LOAD RAW DATASET FROM HUGGINGFACE HUB`"""

raw_datasets = load_dataset("stanfordnlp/imdb")

train_data = raw_datasets["train"]
print(len(train_data))
test_data = raw_datasets["test"]
print(len(test_data))


if CONFIG["train_subset"]:
  train_data = train_data.select(range(CONFIG["train_subset"]))

if CONFIG["test_subset"]:
    test_data  = test_data.select(range(CONFIG["test_subset"]))

print(f"[INFO] Train size: {len(train_data)} | Test size: {len(test_data)}")

"""`BLOCK 4 │ TOKENIZER + TOKENIZATION`"""

tokenizer = AutoTokenizer.from_pretrained(CONFIG["model_name"])

def tokenize_batch(batch):
    """
    Applied to each batch of examples by datasets.map().
    Returns a dict with keys:
      input_ids      – token indices for each token in the sequence
      attention_mask – 1 for real tokens, 0 for [PAD] tokens
      token_type_ids – segment ids (all 0 for single-sentence tasks)
      label          – kept as-is (0 or 1)
    """


    return tokenizer(
        batch["text"],
        max_length = CONFIG["max_length"],
        truncation = CONFIG["truncation"],
        padding    = CONFIG["padding"]
    )

# Map tokenization across all examples in parallel (batched=True is fast)

train_data = train_data.map(tokenize_batch, batched=True)
test_data  = test_data.map(tokenize_batch,  batched=True)

# Tell HuggingFace datasets which columns are tensors and which are the label
train_data = train_data.rename_column("label", "labels")
test_data  = test_data.rename_column("label", "labels")

print(len(train_data[0]))
for key in train_data[0].keys():
    print(key)

print(train_data[0]['input_ids'])

#Remove raw text column
train_data.set_format(type="torch", columns=["input_ids", "attention_mask","token_type_ids", "labels"])
test_data.set_format(type="torch", columns=["input_ids", "attention_mask","token_type_ids", "labels"])

"""`DataLoaders`"""

train_loader = DataLoader(train_data, batch_size=CONFIG["batch_size"], shuffle=True)
test_loader  = DataLoader(test_data, batch_size=CONFIG["batch_size"], shuffle=False)
print(f"{len(train_loader)} | {len(test_loader)}")

"""`MODEL`
#####  AutoModelForSequenceClassification loads BERT + a linear classification head

##### on top of the [CLS] token representation.
##### The head is randomly initialized; all other weights come from the pretrained checkpoint.


"""

model = AutoModelForSequenceClassification.from_pretrained(
    CONFIG["model_name"],
    num_labels = CONFIG["num_labels"]
)
model.to(device)

# Parameter Count

total_params = sum(p.numel() for p in model.parameters())
print(f"Total Parameters: {total_params}")
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"[INFO] Total params: {total_params:,} | Trainable: {trainable_params:,}")

"""`BLOCK 7 │ OPTIMIZER & LR SCHEDULER`

Bias terms — they're just scalar offsets like y = wx + b.
   Shrinking them toward zero adds no regularization benefit
   and can hurt the model's ability to shift activations correctly.


   LayerNorm weights — LayerNorm has two parameters: weight (scale γ)
   and bias (shift β). Their whole job is to rescale and reshift the
   distribution of activations. If you decay them toward zero, you're
   fighting against what LayerNorm is supposed to do. "
"""

no_decay = ["bias", "LayerNorm.weight"]

optimizer_grouped_params = [
    {
        "params"      : [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)],
        "weight_decay": CONFIG["weight_decay"],
    },
    {
        "params"      : [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)],
        "weight_decay": 0.0,
    },
]

optimizer = AdamW(optimizer_grouped_params, lr=CONFIG["lr"])

# Linear warmup then linear decay — avoids catastrophic forgetting at the start
total_steps  = len(train_loader) * CONFIG["num_epochs"]
warmup_steps = int(total_steps * CONFIG["warmup_ratio"])


scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps   = warmup_steps,
    num_training_steps = total_steps,
)

print(f"Total training steps: {total_steps} | Warmup steps: {warmup_steps}")

"""`BLOCK 8 | Training Loop`"""

def train_one_epoch(model, loader, optimizer, scheduler, device, epoch):
    """
    One full pass over the training set.
    Returns average cross-entropy loss for the epoch.
    """
    model.train()          # activates dropout, batch norm in training mode
    total_loss = 0.0

    progress = tqdm(loader, desc=f"Epoch {epoch+1} [Train]", leave=False)

    for step, batch in enumerate(progress):
        # ── Move batch tensors to GPU/CPU ──────────────────────
        input_ids      = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        token_type_ids = batch["token_type_ids"].to(device)
        labels         = batch["labels"].to(device)

        # ── Zero gradients from the previous step ─────────────
        optimizer.zero_grad()

        # ── Forward pass ──────────────────────────────────────
        # The model returns a SequenceClassifierOutput object.
        # When labels are passed, it automatically computes cross-entropy loss.
        outputs = model(
            input_ids      = input_ids,
            attention_mask = attention_mask,
            token_type_ids = token_type_ids,
            labels         = labels,
        )

        loss   = outputs.loss    # scalar cross-entropy loss
        logits = outputs.logits  # shape: (batch_size, num_labels)

        # ── Backward pass ─────────────────────────────────────
        loss.backward()          # compute gradients

        # Gradient clipping: prevents exploding gradients (common for transformers)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        # ── Optimizer + scheduler step ────────────────────────
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()
        progress.set_postfix(loss=f"{loss.item():.4f}", lr=f"{scheduler.get_last_lr()[0]:.2e}")

    avg_loss = total_loss / len(loader)
    return avg_loss

"""` BLOCK 9 │ EVALUATION LOOP`"""

def evaluate(model, loader, device, split_name="Val"):
    """
    Runs inference over `loader` and returns loss, accuracy, and a
    full sklearn classification report (precision, recall, F1).
    """
    model.eval()          # disables dropout, uses running stats for BN
    total_loss   = 0.0
    all_preds    = []
    all_labels   = []

    with torch.no_grad():   # no gradient tracking needed during inference
        progress = tqdm(loader, desc=f"[{split_name}]", leave=False)

        for batch in progress:
            input_ids      = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            token_type_ids = batch["token_type_ids"].to(device)
            labels         = batch["labels"].to(device)

            outputs = model(
                input_ids      = input_ids,
                attention_mask = attention_mask,
                token_type_ids = token_type_ids,
                labels         = labels,
            )

            total_loss += outputs.loss.item()

            # Convert logits → predicted class (argmax over label dimension)
            preds = torch.argmax(outputs.logits, dim=-1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader)
    accuracy = accuracy_score(all_labels, all_preds)
    report   = classification_report(all_labels, all_preds, target_names=["negative", "positive"])
    return avg_loss, accuracy, report

"""`BLOCK 10 │ MAIN TRAINING ENTRY POINT`"""

print("\n" + "="*60)
print("  Starting Fine-Tuning")
print("="*60)

best_accuracy = 0.0

for epoch in range(CONFIG["num_epochs"]):
    # ── Train ─────────────────────────────────────────────────
    train_loss = train_one_epoch(model, train_loader, optimizer, scheduler, device, epoch)

    # ── Evaluate on test set ──────────────────────────────────
    test_loss, test_acc, test_report = evaluate(model, test_loader, device, split_name="Test")

    print(f"\nEpoch {epoch+1}/{CONFIG['num_epochs']}")
    print(f"  Train Loss : {train_loss:.4f}")
    print(f"  Test  Loss : {test_loss:.4f}  |  Accuracy : {test_acc*100:.2f}%")
    print(f"\n{test_report}")

    # ── Save best model ───────────────────────────────────────
    if test_acc > best_accuracy:
        best_accuracy = test_acc
        model.save_pretrained(CONFIG["save_path"])
        tokenizer.save_pretrained(CONFIG["save_path"])
        print(f"  [SAVED] New best model → accuracy: {best_accuracy*100:.2f}%")

print("\n" + "="*60)
print(f"  Training complete.  Best Test Accuracy: {best_accuracy*100:.2f}%")
print(f"  Model saved to: {CONFIG['save_path']}")
print("="*60)

"""`BLOCK 11 │ INFERENCE ON NEW TEXT  (post-training usage)`"""

def predict(texts: list[str], model_path: str = CONFIG["save_path"]) -> list[dict]:
    """
    Load the saved model and run inference on a list of raw strings.

    Args:
        texts      : list of review strings
        model_path : path to the saved fine-tuned model directory

    Returns:
        list of dicts with keys: 'text', 'label', 'confidence'
    """
    # Load saved artifacts
    inf_tokenizer = AutoTokenizer.from_pretrained(model_path)
    inf_model     = AutoModelForSequenceClassification.from_pretrained(model_path)
    inf_model     = inf_model.to(device)
    inf_model.eval()

    id2label = {0: "negative", 1: "positive"}
    results  = []

    # Tokenize in one batch
    encoding = inf_tokenizer(
        texts,
        max_length  = CONFIG["max_length"],
        truncation  = CONFIG["truncation"],
        padding     = CONFIG["padding"],
        return_tensors = "pt",
    )

    with torch.no_grad():
        outputs = inf_model(
            input_ids      = encoding["input_ids"].to(device),
            attention_mask = encoding["attention_mask"].to(device),
        )
        probs  = torch.softmax(outputs.logits, dim=-1)   # convert logits → probabilities
        preds  = torch.argmax(probs, dim=-1).cpu().numpy()
        confs  = probs.max(dim=-1).values.cpu().numpy()

    for text, pred, conf in zip(texts, preds, confs):
        results.append({
            "text"      : text[:80] + "..." if len(text) > 80 else text,
            "label"     : id2label[pred],
            "confidence": round(float(conf), 4),
        })

    return results

sentences = [
    "The customer support team resolved my issue quickly and professionally.",
    "I absolutely loved the movie; the acting and storyline were outstanding.",
    "This laptop performs exceptionally well and exceeded my expectations.",
    "The restaurant served delicious food and provided excellent service.",
    "I'm very happy with the quality of this product and would recommend it to others."
]

# ── Quick smoke test ──────────────────────────────────────────
sample_reviews = [
    "The customer support team resolved my issue quickly and professionally.",
    "I absolutely loved the movie; the acting and storyline were outstanding.",
    "This laptop performs exceptionally well and exceeded my expectations.",
    "The restaurant served delicious food and provided excellent service.",
    "I'm very happy with the quality of this product and would recommend it to others."
]

print("\n[INFERENCE DEMO]")
for res in predict(sample_reviews):
    print(f"  [{res['label'].upper():8s}  {res['confidence']:.2%}]  {res['text']}")

negative_sentences = [
    "The application keeps crashing, making it almost impossible to use.",
    "I was extremely disappointed by the poor quality of the product.",
    "The service was slow, and the staff seemed uninterested in helping customers.",
    "This was a complete waste of time and money.",
    "The package arrived damaged and several items were missing."
]


print("\n[INFERENCE DEMO]")
for res in predict(negative_sentences):
    print(f"  [{res['label'].upper():8s}  {res['confidence']:.2%}]  {res['text']}")